name: Publish Package to npm

on:
  push:
    branches:
      - master
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'
          scope: '@gonextgames'

      - name: Clean install dependencies
        run: |
          rm -f package-lock.json
          npm install --no-package-lock

      - name: Build
        run: npm run build

      - name: Copy CSS files to dist
        run: |
          find src -name "*.css" -exec cp --parents {} dist \;

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      